### ISSUE TITLE
State command shows wrong "previous closing Price"

### ISSUE THREAD

**Issue by johnerfx** [gnosis/dx-services#52]
Hi, 
I think "State" command shows wrong "Previous closing Price". 
As we see on an image, prices are different so they can't relate 100% to themselves(to do that, they should be equal).
![rdnweth](https://user-images.githubusercontent.com/20050269/53698325-71ecfe80-3ddb-11e9-9546-e3b53098e8ac.png)

**Comment by dasanra** [comment]
Thank you for reporting.
I think I know why this bug should be happening. I'll add more info here when it's reviewed/solved

**Comment by dasanra** [comment]
This issue is solved in v2.0.5

https://github.com/gnosis/dx-services/releases/tag/v2.0.5
